[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = " IDlab-Turtlebot"
authors = [{name = "Yuri Durodie", email = "yuri.durodie@vub.be"}]
dynamic = ["0.1", "First version sufficient to allow Jono to operate the robot him self (hopefully.) ;) "]
